import { chromium } from "playwright-core";
import { launchOptions } from "./_browser.mjs";
const B = await chromium.launch(launchOptions());
const p = await (await B.newContext({ viewport: { width: 1920, height: 1080 } })).newPage();
const errs = []; p.on("pageerror", e => errs.push(String(e.message).slice(0,80)));
await p.goto("http://127.0.0.1:3077/", { waitUntil: "domcontentloaded" });
const animName = await p.evaluate(() => getComputedStyle(document.querySelector(".line-inner")).animationName);
await p.waitForTimeout(1500);
await p.evaluate(() => document.querySelector("#arsitektur").scrollIntoView({ behavior: "instant", block: "start" }));
await p.waitForTimeout(900);
const revealed = await p.evaluate(() => document.querySelector("#arsitektur")?.classList.contains("in"));
const spin = await p.evaluate(() => getComputedStyle(document.querySelector(".spin")).animationName);
await p.goto("http://127.0.0.1:3077/dashboard/pusat/utilization", { waitUntil: "load" });
await p.waitForTimeout(1600);
const box = await p.evaluate(() => { const m = document.querySelector("main > div"); const r = m.getBoundingClientRect(); return { left: Math.round(r.left), width: Math.round(r.width), vw: innerWidth, ratio: (r.width/(innerWidth-256)).toFixed(2) }; });
console.log(JSON.stringify({ animName, spin, revealed, box, errs: errs.length ? errs : "clean" }));
await B.close();
